<?php
function e(mixed $value): string { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }
function money(mixed $value): string { return number_format((float) $value, 2, ',', ' ') . ' ' . CURRENCY; }
$isSale = $movement['type_mouvement'] === 'VENTE';
$documentType = $isSale ? 'FACTURE DE VENTE' : 'FACTURE D’ACHAT';
$partyLabel = $isSale ? 'CLIENT' : 'FOURNISSEUR';
$partyName = $movement['tier_nom'] ?: ($isSale ? 'Client comptoir' : 'Fournisseur non précisé');
$formatNames = ['a4' => 'PDF / A4', 'pos80' => 'POS-80', 'pos50' => 'POS-50'];
?>
<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e($documentType) ?> #<?= e($movement['id']) ?> | <?= e(APP_NAME) ?></title><link rel="icon" type="image/x-icon" href="<?= BASE_URL ?>/public/assets/favicon.ico"><link rel="stylesheet" href="<?= BASE_URL ?>/public/assets/style.css"></head><body class="print-document invoice-<?= e($format) ?>"><main class="document-sheet"><header class="document-header"><div><div class="document-brand"><img src="<?= BASE_URL ?>/public/assets/logo.png" alt="Logo FURU"><strong>FURU / HAOJUE</strong></div><p class="eyebrow"><?= e($documentType) ?></p><h1>#<?= e(str_pad((string) $movement['id'], 6, '0', STR_PAD_LEFT)) ?></h1></div><div class="document-meta"><strong><?= date('d/m/Y H:i', strtotime($movement['date_mouvement'])) ?></strong><span><?= e($formatNames[$format]) ?></span><span><?= e($movement['mode_paiement'] ?: 'Paiement non précisé') ?></span></div></header><section class="invoice-parties"><div><span><?= e($partyLabel) ?></span><strong><?= e($partyName) ?></strong></div><div><span>ÉMETTEUR</span><strong>Garage FURU / HAOJUE</strong></div></section><table class="invoice-table"><thead><tr><th>Désignation</th><th>Référence</th><th>Qté</th><th>Prix unitaire</th><th>Total</th></tr></thead><tbody><tr><td><strong><?= e($movement['produit_nom'] ?? 'Référence supprimée') ?></strong></td><td><?= e($movement['sku'] ?? '—') ?></td><td><?= e($movement['quantite']) ?></td><td><?= money($movement['prix_unitaire']) ?></td><td><strong><?= money($movement['montant_total']) ?></strong></td></tr></tbody></table><div class="invoice-total"><span>Total <?= $isSale ? 'à payer' : 'de l’achat' ?></span><strong><?= money($movement['montant_total']) ?></strong></div><footer class="document-footer">Document <?= $isSale ? 'de vente' : 'd’achat' ?> généré par Garage FURU / HAOJUE.</footer><div class="document-actions"><a class="button <?= $format === 'a4' ? 'button-primary' : 'button-outline' ?>" href="<?= BASE_URL ?>/index.php?page=facture&id=<?= e($movement['id']) ?>&format=a4">PDF / A4</a><a class="button <?= $format === 'pos80' ? 'button-primary' : 'button-outline' ?>" href="<?= BASE_URL ?>/index.php?page=facture&id=<?= e($movement['id']) ?>&format=pos80">POS-80</a><a class="button <?= $format === 'pos50' ? 'button-primary' : 'button-outline' ?>" href="<?= BASE_URL ?>/index.php?page=facture&id=<?= e($movement['id']) ?>&format=pos50">POS-50</a><button class="button button-primary" onclick="window.print()">Imprimer / PDF</button><a class="button button-ghost" href="<?= BASE_URL ?>/index.php?page=mouvements">Retour</a></div></main></body></html>
